---
language: node_js
node_js:
  - "4"

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

env:
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
  
deploy:
  provider: npm
  email: null@ember.theater
  api_key:
    secure: xGL6QNY4So4CiFRzrN1W6KFILcMpD4C28bNZFSETMNY6VWiB4+KAGrMcKAaR5d0yWEgDMrVpS8noGnJYGLzPUmVmXdra05WSZc/fjmLGFKrU1DkKMFLfnxTQuLqFGfX0pfVdTDmczH0FX1hlk7dRyOone4JoFShrd/mIBUzO4ITfPHcldqwMqDKy18F3bdh+5gPb/PPlFeW/r3WslyhMfKnjqNCGe8B1kgMJL1nNuviatzJeUBuwfBiKRfzblXEhr684ggA15dzQh2JqV1p3Ji4iy71AeNeaBYdAAWQenJuKnDqKSLvXxQakYokIwqNPHcSw8ceGqAV97oThdRWy6LVZKWipTlVqtmr9tqUDQtS2AOQdbXNwuHXm+QcGqSp5X8u+9wT2BJkJInGdXIxoznYzinnVArq/F3aoG4MzegxyM/ASQ3dgH86MLV2xzi7u46yj4f6t7KvR5gWm2ynbDnOnF4iFK1dZqSGNYRxx9YOorIghV4c98B1mdWR6Cu+nPN/eHnReB7vAiesluvGTzdvV7/f+D427BzgFH8oEan3kVcDYmnUeF6bwe5ocmuplJhemXvNV8CjTbRobjfqxL4ziOzwN6oA38kh6dXXqBm3aEMsgkwx1dyJA6iPsC2Vh2CAJw/K/47Qh8K9p6IdoaG4VYqlRZhXxcE5dQ2+9AA0=
  on:
    tags: true
    repo: null-null-null/ember-letter-by-letter
